sonar.projectKey=autoparts-frontend
sonar.projectName=AutoParts WebHub Frontend
sonar.projectVersion=1.0.0

# Paths to sources
sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.spec.ts,node_modules/**

# Connection to SonarQube Server
sonar.host.url=http://localhost:9000

# Authentication Token (generar en la interfaz de SonarQube y pegar aquí, o pasar por línea de comandos)
sonar.token=squ_b0030f669aad254ea3b7c8d2e35139a0429b2e1b
